# **Notebook 5 – Aggregation Features**

In [26]:
import pandas as pd 
df = pd.read_csv("hospital_patient_treatment_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               2000 non-null   object
 1   Visit_ID                 2000 non-null   object
 2   Age                      2000 non-null   int64
 3   Gender                   2000 non-null   object
 4   Department               2000 non-null   object
 5   Diagnosis                2000 non-null   object
 6   Insurance_Type           1985 non-null   object
 7   Treatment_Type           2000 non-null   object
 8   Length_of_Stay           2000 non-null   int64
 9   Medication_Count         2000 non-null   int64
 10  Lab_Test_Count           2000 non-null   int64
 11  Treatment_Cost           2000 non-null   float64
 12  Doctor_Experience_Years  1990 non-null   float64
 13  Patient_Satisfaction     1980 non-null   float64
 14  Admission_Date           2000 non-null   object
 15  Discharge_Date           2000 non-null   object
 16  Readmission              2000 non-null   object
dtypes: float64(3), int64(4), object(10)
memory usage: 265.8+ KB

## **1. Count**

**Understand the Concept**

* Count means finding how many records are present in a group.
* It helps us understand the number of patients, visits, or treatments.

**Demonstrate the Concept**

**Example:**

* Count the number of visits for each department.

In [27]:
department_visit_count = (df.groupby("Department")["Visit_ID"].count().reset_index(name="Visit_Count"))
department_visit_count

         Department  Visit_Count
0        Cardiology          275
1       Dermatology          285
2  General Medicine          281
3         Neurology          343
4          Oncology          268
5       Orthopedics          253
6        Pediatrics          295

**Explanation**

* groupby() groups the data by Department.
* count() counts the number of visits in each department.

**Justify Your Feature**

* I created this feature to understand the number of patient visits in each department.

## **2. Sum**

**Understand the Concept**

* Sum means adding all values together.
* It helps find the total value for a group.

**Demonstrate the Concept**

**Example:**

* Calculate the total treatment cost for each department.

In [28]:
department_cost = (df.groupby("Department")["Treatment_Cost"].sum().reset_index(name="Total_Treatment_Cost"))
department_cost

         Department  Total_Treatment_Cost
0        Cardiology           20199955.16
1       Dermatology           21104311.09
2  General Medicine           21076078.89
3         Neurology           26595510.01
4          Oncology           20543114.86
5       Orthopedics           19987442.99
6        Pediatrics           22069763.69

**Explanation**

* groupby() groups the data by Department.
* sum() adds all treatment costs in each department.
  
**Justify Your Feature**

* I created this feature to understand the total treatment cost for each department.

## **3. Mean**

**Understand the Concept**

* Mean means calculating the average value.
* It helps understand the typical value of a group.

**Demonstrate the Concept**

**Example:**

* Calculate the average treatment cost for each department.

In [29]:
department_mean_cost = (df.groupby("Department")["Treatment_Cost"].mean().reset_index(name="Average_Treatment_Cost"))
department_mean_cost

         Department  Average_Treatment_Cost
0        Cardiology            73454.382400
1       Dermatology            74050.214351
2  General Medicine            75003.839466
3         Neurology            77537.930058
4          Oncology            76653.413657
5       Orthopedics            79001.750949
6        Pediatrics            74812.758271

**Explanation**

* groupby() groups the data by Department.
* mean() calculates the average treatment cost in each department.

**Justify Your Feature**

* I created this feature to understand the average treatment cost for each department.

## **4. Median**

**Understand the Concept**

* Median is the middle value when data is arranged in order.
* It is useful when the data contains very high or very low values.

**Demonstrate the Concept**

**Example:**

* Calculate the median treatment cost for each department.

In [30]:
department_median_cost = (df.groupby("Department")["Treatment_Cost"].median().reset_index(name="Median_Treatment_Cost"))
department_median_cost

         Department  Median_Treatment_Cost
0        Cardiology              76333.460
1       Dermatology              71696.970
2  General Medicine              73897.840
3         Neurology              76172.290
4          Oncology              77569.005
5       Orthopedics              76678.380
6        Pediatrics              75540.060

**Explanation**

* groupby() groups the data by Department.
* median() finds the middle treatment cost in each department.

**Justify Your Feature**

* I created this feature to understand the typical treatment cost without the strong effect of extreme values.

## **5. Minimum**

**Understand the Concept**

* Minimum means finding the smallest value in a group.
* It helps identify the lowest value recorded.

**Demonstrate the Concept**

**Example:**

* Find the minimum treatment cost for each department.

In [31]:
department_min_cost = (df.groupby("Department")["Treatment_Cost"].min().reset_index(name="Minimum_Treatment_Cost"))
department_min_cost

         Department  Minimum_Treatment_Cost
0        Cardiology                 1696.00
1       Dermatology                 2097.75
2  General Medicine                 2001.76
3         Neurology                 1549.03
4          Oncology                 1546.00
5       Orthopedics                 5805.42
6        Pediatrics                 2274.06

**Explanation**

* groupby() groups the data by Department.
* min() finds the smallest treatment cost in each department.
* The result shows the lowest treatment cost for each department.

**Justify Your Feature**

* I created this feature to identify the minimum treatment cost in each department.

## **6. Maximum**

**Understand the Concept**

* Maximum means finding the largest value in a group.
* It helps identify the highest value recorded.

**Demonstrate the Concept**

**Example:**

* Find the maximum treatment cost for each department.

In [32]:
department_max_cost = (df.groupby("Department")["Treatment_Cost"].max().reset_index(name="Maximum_Treatment_Cost"))
department_max_cost

         Department  Maximum_Treatment_Cost
0        Cardiology               148397.17
1       Dermatology               149988.84
2  General Medicine               149728.95
3         Neurology               149220.92
4          Oncology               149384.68
5       Orthopedics               149339.07
6        Pediatrics               149919.67

**Explanation**

* groupby() groups the data by Department.
* max() finds the highest treatment cost in each department.
* The result shows the maximum treatment cost for each department.

**Justify Your Feature**

* I created this feature to identify the highest treatment cost in each department.

## **7. Standard Deviation**

**Understand the Concept**

* Standard deviation measures how much values vary from the average.
* A low value means the values are closer together.
* A high value means the values are more spread out.

**Demonstrate the Concept**

**Example:**

* Calculate the variation in treatment costs for each department.

In [33]:
department_cost_std = (df.groupby("Department")["Treatment_Cost"].std().reset_index(name="Treatment_Cost_Std"))
department_cost_std

         Department  Treatment_Cost_Std
0        Cardiology        43688.083192
1       Dermatology        43387.815401
2  General Medicine        42996.704921
3         Neurology        43944.148149
4          Oncology        42609.710873
5       Orthopedics        40359.029325
6        Pediatrics        45756.676156

**Explanation**

* groupby() groups the data by Department.
* std() measures the variation in treatment costs.
* A higher value means treatment costs vary more within the department.

**Justify Your Feature**

* I created this feature to understand the variation in treatment costs across departments.

## **8. Group-Based Aggregation**

**Understand the Concept**

* Group-based aggregation calculates multiple statistics for different groups.
* It allows us to summarize data using more than one measure.

**Demonstrate the Concept**

**Example:**

* Calculate the number of visits, total treatment cost, and average treatment cost for each department.

In [34]:
department_summary = (df.groupby("Department").agg(Visit_Count=("Visit_ID", "count"),
                                                   Total_Treatment_Cost=("Treatment_Cost", "sum"),
                                                   Average_Treatment_Cost=("Treatment_Cost", "mean")).reset_index())
department_summary

         Department  Visit_Count  Total_Treatment_Cost  Average_Treatment_Cost
0        Cardiology          275           20199955.16            73454.382400
1       Dermatology          285           21104311.09            74050.214351
2  General Medicine          281           21076078.89            75003.839466
3         Neurology          343           26595510.01            77537.930058
4          Oncology          268           20543114.86            76653.413657
5       Orthopedics          253           19987442.99            79001.750949
6        Pediatrics          295           22069763.69            74812.758271

**Explanation**

* groupby() creates groups based on Department.
* agg() applies multiple aggregation functions.

**Justify Your Feature**

* I created these features to get a complete summary of department-level patient activity.

## **9. Patient-Level Aggregation**

**Understand the Concept**

* Patient-level aggregation summarizes information for each patient.
* It combines multiple visits of the same patient into useful values.

**Demonstrate the Concept**

**Example:**

* Calculate each patient's total treatment cost, visit count, and average treatment cost.

In [35]:
patient_summary = (df.groupby("Patient_ID")  .agg(Visit_Count=("Visit_ID", "count"),
                                                  Total_Treatment_Cost=("Treatment_Cost", "sum"),
                                                  Average_Treatment_Cost=("Treatment_Cost", "mean")).reset_index())
patient_summary.head()

  Patient_ID  Visit_Count  Total_Treatment_Cost  Average_Treatment_Cost
0     P00001            4             355569.52            88892.380000
1     P00002            4             192503.47            48125.867500
2     P00003            3             120031.93            40010.643333
3     P00004            2             115028.99            57514.495000
4     P00005            5             255941.19            51188.238000

**Explanation**

* groupby() groups all visits belonging to the same Patient_ID.
* count() calculates the number of visits.
* sum() calculates total treatment cost.
* mean() calculates average treatment cost.

**Justify Your Feature**

* I created these features to understand each patient's overall treatment history.

## **10. Treatment-Level Aggregation**

**Understand the Concept**

* Treatment-level aggregation summarizes information for each treatment type.
* It helps compare different treatments.

**Demonstrate the Concept**

**Example:**

* Calculate the number of patients and average treatment cost for each treatment type.

In [36]:
treatment_summary = (df.groupby("Treatment_Type").agg( Visit_Count=("Visit_ID", "count"),
                                                       Total_Treatment_Cost=("Treatment_Cost", "sum"),
                                                       Average_Treatment_Cost=("Treatment_Cost", "mean")).reset_index())
treatment_summary

  Treatment_Type  Visit_Count  Total_Treatment_Cost  Average_Treatment_Cost
0     Counseling          355           27449554.69            77322.689268
1     Medication          317           24781628.55            78175.484385
2    Observation          338           25897903.29            76621.015651
3  Physiotherapy          313           21820004.62            69712.474824
4      Radiation          352           27904907.12            79275.304318
5        Surgery          325           23722178.42            72991.318215

**Explanation**

* groupby() groups the data by Treatment_Type.
* count() calculates the number of visits for each treatment.
* sum() calculates the total treatment cost.
* mean() calculates the average treatment cost.

**Justify Your Feature**

* I created these features to compare treatment usage and treatment costs.

## **11. Transaction-Level Aggregation**

**Understand the Concept**

* Transaction-level aggregation summarizes information for each hospital visit.
* It combines related values to create a useful visit-level feature.

**Demonstrate the Concept**

**Example:**

* Calculate the total activity count for each visit using medication and lab test counts.

In [37]:
df["Total_Clinical_Activities"] = (df["Medication_Count"] +  df["Lab_Test_Count"])
df[["Visit_ID","Medication_Count","Lab_Test_Count","Total_Clinical_Activities"]].head()

   Visit_ID  Medication_Count  Lab_Test_Count  Total_Clinical_Activities
0  VIS01164                 1               1                          2
1  VIS01371                 1              10                         11
2  VIS00447                 0               3                          3
3  VIS01433                 2               7                          9
4  VIS01522                 1               1                          2

**Explanation**

* The medication count and lab test count are added together.
* The result is stored as Total_Clinical_Activities.
* It represents the total number of recorded medication and lab-test activities for a visit.

**Justify Your Feature**

* I created this feature to measure the overall clinical activity during each patient visit.